version: '3.9'

services:
  db_ignite:
    image: postgres
    container_name: rentx_bd
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx_app
    ports:
      - 4444:4444
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local